package rwcsim.basicutils.dials;

public enum Face {
    MARCH,
    SHIFT,
    REFORM,
    ATTACK_MELEE,
    ATTACK_RANGED,
    RALLY,
    SKILL,
    MOVE_MOD_CHARGE,
    MOVE_MOD_TURN,
    MOVE_MOD_TURNING_CHARGE,
    MOVE_MOD_WHEEL,
    DEFEND,
    ENHANCE_HIT,
    ENHANCE_SURGE,
    ENHANCE_MORALE,
    ENHANCE_ACCURACY,
    ENHANCE_MORTAL_STRIKE,
    BLANK;
}
